#!/bin/sh

###-------------------------------------------------------------------
### File    : erjik
### Author  : Aleksey Morarash <aleksey.morarash@gmail.com>
### Created : 6 Jul 2012
### License : FreeBSD
### Description : erjik start script wrapper
###
###-------------------------------------------------------------------

exec sudo -n -u erjik -i /usr/share/erjik/start.sh

