#!/bin/sh -e

###-------------------------------------------------------------------
### File    : erjik-ping
### Author  : Aleksey Morarash <aleksey.morarash@gmail.com>
### Created : 6 Jul 2012
### License : FreeBSD
### Description : erjik pinger tool
###-------------------------------------------------------------------

. "`dirname $0`"/erjik-functions
exec erl -noinput -sname "erjik_pinger$RANDOM" \
    -s erjik ping > /dev/null 2>&1

