#!/bin/sh -e

###-------------------------------------------------------------------
### File    : erjik-hup
### Author  : Aleksey Morarash <aleksey.morarash@gmail.com>
### Created : 6 Jul 2012
### License : FreeBSD
### Description : make erjik to reload configurations and reopen
###               log file without restart.
###-------------------------------------------------------------------

. "`dirname $0`"/erjik-functions
exec erl -noinput -sname "erjik_hupper$RANDOM" \
    -s erjik hup > /dev/null 2>&1

