#!/bin/sh -e

###-------------------------------------------------------------------
### File    : erjik
### Author  : Aleksey Morarash <aleksey.morarash@gmail.com>
### Created : 6 Jul 2012
### License : FreeBSD
### Description : erjik start script
###-------------------------------------------------------------------

. "`dirname $0`"/erjik-functions
exec erl -noshell -sname erjik \
    -erjik_config "{{CONF_DIR}}/erjik.conf" \
    -erjik_log "{{LOG_DIR}}/erjik.log" \
    -s erjik

