#!/bin/sh -e

###-------------------------------------------------------------------
### File    : erjik-stop
### Author  : Aleksey Morarash <aleksey.morarash@gmail.com>
### Created : 6 Jul 2012
### License : FreeBSD
### Description : stops erjik.
###-------------------------------------------------------------------

. "`dirname $0`"/erjik-functions
exec erl -noinput -sname "erjik_stopper$RANDOM" \
    -s erjik stop_remote > /dev/null 2>&1

